- name: Ensure autostart directory exists
  file:
    path: "~/.config/autostart"
    state: directory

- name: Remove unwanted autostart applications
  file:
    path: "~/.config/autostart/{{ item }}"
    state: absent
  with_items:
  - plank.desktop

- name: Install autostart applications
  copy:
    src: "{{item}}"
    dest: "~/.config/autostart/{{ item }}"
    mode: 0664
  with_items:
  - setxkbmap.desktop

- name: Symlink autostart applications
  file:
    src: "/usr/share/applications/{{item}}"
    dest: "~/.config/autostart/{{ item }}"
    state: link
    force: true
  with_items:
  - com.yubico.yubioath.desktop
