- name: Retrieve UUID for current budgie-panel instance(s)
  ansible.builtin.command:
    argv:
    - dconf
    - read
    - /com/solus-project/budgie-panel/panels
  register: budgie_panels_dconf_output
  check_mode: false
  changed_when: 'budgie_panels_dconf_output.stdout != "[''c01dale8-1977-1138-2187-deadbeef0000'']"'
  failed_when: false

- name: Remove existing budgie-panel(s) configuration
  ansible.builtin.command:
    argv:
    - dconf
    - reset
    - -f
    - /com/solus-project/budgie-panel/
  when: budgie_panels_dconf_output.changed
  notify:
  - restart-budgie-panel

- name: Retrieve UUIDs for current Raven widgets
  command:
    argv:
    - dconf
    - read
    - /org/buddiesofbudgie/budgie-desktop/raven/widgets/uuids
  register: budgie_raven_widgets_dconf_output
  check_mode: false
  changed_when: '"c01dale8-1977-1138-2187-deadbeefd001" not in budgie_raven_widgets_dconf_output.stdout'
  failed_when: false

- name: Remove existing Raven widgets configuration
  command:
    argv:
    - dconf
    - reset
    - -f
    - /org/buddiesofbudgie/budgie-desktop/raven/widgets/
  when: budgie_raven_widgets_dconf_output.changed
  notify:
  - restart-budgie-panel

- name: Set dconf values from configuration file
  ansible.builtin.command:
    argv:
    - dconf
    - load
    - /
    stdin: "{{ lookup('file', item) }}"
  with_first_found:
  - files:
    - 'dconf/dconf-settings-{{ ansible_facts["distribution"] | lower }}-{{ ansible_facts["distribution_version"] }}.ini'
  - skip: true
  notify:
  - restart-budgie-panel

- name: Set budgie-panel menu label
  community.general.dconf:
    key: '/org/solus-project/budgie-panel/instance/budgie-menu/{c01dale8-1977-1138-2187-deadbeefa000}/menu-label'
    value: "'{{ ansible_facts['hostname'] }}'"
