gnome_extensions:
  user:
  - copyous@boerdereinar.dev
  - dash-to-panel@jderose9.github.com
  - just-perfection-desktop@just-perfection
  - simple-weather@romanlefler.com
  system:
  - drive-menu@gnome-shell-extensions.gcampax.github.com
