repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.6
    hooks:
      - id: remove-tabs
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.16.0
    hooks:
      - id: pretty-format-yaml
        args: [--preserve-quotes, --autofix, --offset, "2"]
  - repo: local
    hooks:
      - id: betterleaks
        name: betterleaks
        entry: betterleaks git . --pre-commit --staged --redact
        language: system
        pass_filenames: false
      - id: shellcheck
        name: shellcheck
        language: system
        entry: shellcheck
        types: [shell]
      - id: taplo
        name: taplo
        entry: taplo format
        language: system
        types: [toml]
