#!/bin/sh

set -e

if [ "$(id -u)" -eq 0 ]; then
    echo "Error: Run this as a normal user" >&2
    exit 1
fi

if [ ! -x "$(command -v ansible 2>&1)" ]; then
    (
        set -x
        sudo apt install -y ansible-core
    )
fi

set -x
ansible-galaxy install -r requirements.yml
ANSIBLE_NOCOWS=1 ansible-playbook -Ki hosts.localhost local.yml "${@}"
