- name: Install apt packages
  ansible.builtin.apt:
    pkg:
    - audacity
    - blender
    - build-essential
    - curl
    - dconf-cli
    - dconf-editor
    - dkms
    - easytag
    - exiv2
    - flake8
    - fonts-lato
    - fonts-powerline
    - fonts-roboto
    - fonts-roboto-slab
    - gifsicle
    - gimp
    - gnome-tweaks
    - gnucash
    - gparted
    - gscan2pdf
    - handbrake
    - handbrake-cli
    - htop
    - iftop
    - imagemagick
    - inkscape
    - jq
    - ldap-utils
    - lsdvd
    - mesa-utils
    - minicom
    - mkvtoolnix
    - nfs-common
    - nmap
    - openscad
    - pandoc
    - pdftk-java
    - proxytunnel
    - pv
    - python-is-python3
    - python3-pip
    - scdaemon
    - screen
    - shellcheck
    - smbclient
    - sqlite3
    - tmux
    - tofrodos
    - traceroute
    - udiskie
    - universal-ctags
    - unrar
    - vim-gtk3
    - vlc
    - whois
    - xclip
    - yq
    - yubikey-manager
    state: present
    update_cache: true
    cache_valid_time: 600
  become: true

- name: 'Include Docker package tasks'
  ansible.builtin.include_tasks: docker.yml

- name: 'Include Google Chrome package tasks'
  ansible.builtin.include_tasks: google-chrome.yml

- name: 'Include Mozilla package tasks'
  ansible.builtin.include_tasks: mozilla.yml

- name: 'Include Signal package tasks'
  ansible.builtin.include_tasks: signal.yml
