- name: Check if Google Chrome is installed
  command: dpkg-query -l google-chrome-stable
  register: google_chrome_installed
  failed_when: google_chrome_installed.rc > 1
  check_mode: false
  changed_when: false

- name: Install Google Chrome
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    state: present
  become: true
  when: google_chrome_installed.rc != 0
