- name: Install Libreoffice Fresh PPA
  ansible.builtin.deb822_repository:
    name: libreoffice
    uris:
    - "https://ppa.launchpadcontent.net/libreoffice/ppa/ubuntu/"
    suites:
    - "{{ ansible_facts['distribution_release'] }}"
    components:
    - main
    signed_by: |-
      -----BEGIN PGP PUBLIC KEY BLOCK-----
      .
      mI0ETRuApgEEAKFfVq0Yu0rBdnipWkI9WOW6X1xrzrpSWE+bTakWbNASr3f5RENb
      k0JEOGayoyIynRj2GHxAtD116BApkF3IdtikrEBDZKirgUOlq9EpSyP0EwbP/n40
      p9VcWH4KHyR9pILKuiU1t0u70VSakvB1+KkOqs2oei0TFnDYbYH5pmWHABEBAAG0
      J0xhdW5jaHBhZCBQUEEgZm9yIExpYnJlT2ZmaWNlIFBhY2thZ2luZ4i4BBMBAgAi
      BQJNG4CmAhsDBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRCD+6F1E3i0ROAG
      A/9otE7tGoigHssjm9SG9vwVTGYF+0QQX2uwiQJmChXdqtt1y+YRv5bq61KGfu46
      DNc0QlJIgaOW+6hp/L5QwTrNIp7psjDPUjTQ0qo0ZSRb67WJjNKeR78PGtxYRNH+
      S67HBEFatbF7EPVuoqTS38myroYRQtTHuXD2zwqM8WSPNokCHAQQAQIABgUCTTBX
      PwAKCRC5byMArRHL7tm0EADDPtdJwqu4RQGdbI1KONhkoh5y5H4aEc0jQDe1VjTh
      XrZYnWrkBZvb3dhwtiA4CT+hWiZQnilue+SfACCdjdNQY6neP1Y4czLq6ApErVZa
      9rL7tvMxrrhShLLxTDBrLrXDGsLE9AGKwe4GicuB0rh1JWiWawhygu1CZhm+7paX
      p7njh+IPbRTf3q8hHLWVGeFyaro7fQiUmfi/q5ljsqMfTBDdPmL4+vOpBTvFNsUv
      U2vHii2C+/p/la3xZM6r3j7O00FRDMPr64dt3hDkJgOKrX2Cxat6w6Nuw+yVw2k6
      9WgP3zZZEieIKytBoEJ9nLycdJhdeLToJ/7R2iZJBhdUjpMbzyQ0c9YiaUKs8YP6
      wZftZHbG7JsiHXpUkMqlnz9PDBWm1K3bXbaClcT9h6ISzeYqKspLjJ4PPMejELiI
      7X/hNQ2+LlCe8epjENyNCC0/pdzMudOpwkgc3D8TkLo1+EH64gPRPNzR4EdedGWn
      UpWiNwtkz8eSh5EYC2Ucv1NwUfaj77GDnTprX0bOGWbYp+OiT6OxIKpospfcNhqZ
      1YxtNVM8d8cFCQKU4LiDMQZL0uQm7dsFFmUwR5rTr2ZCY+JNUfAoE7IdGWo9St50
      DIVyEhPNZuwiYy5nX54MIWmhCpzv8Yr2SXtxYcfMZ6qxaGxYyyD1d3T0WrqjxNN+
      EokBnAQRAQoABgUCTqmikwAKCRCg8hPxRutYHyecDACQ9orO4sA3BMPGUN6VKcSP
      nIu5UiaYHoucE2vrq5BBuLSgKM/T77YtFWXWEMcPJQH89b4E/O92Dz+qn1Rlb4jI
      5yK0yvxPE8i8A0JvEa7IdQSfYn/NZFuG7wDNDopNj9QjZv2QHvu4ZanDrcP+FWUw
      BujVMJTTP60UPwWSL6J0N0aKGWJ8OBNo0XrmYrAacvEIt6ytu79liUeO1afw97yi
      fT9QafYlW2sziJEfyqHKnHRaC7fAhPM8p+x0G1EeKO7iQsTqZHIGmEDoSIIvNhEa
      elP8xZ8mRLdeA5B+33mbb2KSjEzXu3GLXQ7L9TxtNu1n5M40Tcu6algWTqwnnqEh
      afN4KKt5DNt4v+F7igEQEmKj7MHsHZV5f/lXvWci84T/nqE9KcBF7QsGjzEHtpz1
      dTZdZk6pJvTOpY52QURWhIlsyeYbG7GzSsRIZOoS4CD+sMEgmlBVQ9AwQC5tvWWa
      otnR4sNTPVp/o6NiPtrQi+LjAWS39c4pfOgM38J3Fik=
      =by/p
      -----END PGP PUBLIC KEY BLOCK-----
    state: present
    enabled: true
  register: libreoffice_ppa
  become: true

- name: Upgrade to install newer LibreOffice packages
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
    cache_valid_time: "{{ 0 if libreoffice_ppa.changed else 600 }}"
  become: true

- name: Install LibreOffice
  ansible.builtin.apt:
    pkg:
    - libreoffice
    state: present
    update_cache: true
    cache_valid_time: 600
  become: true
