- name: Install Libreoffice Fresh PPA
  ansible.builtin.apt_repository:
    repo: ppa:libreoffice/ppa
  register: libreoffice_ppa
  become: true

- name: Upgrade to install newer LibreOffice packages
  apt:
    update_cache: true
    upgrade: dist
  become: true
  when: libreoffice_ppa.changed

- name: Install LibreOffice
  apt:
    pkg:
    - libreoffice
    state: present
  become: true
