- name: Check if the Libreoffice Fresh PPA is installed
  command:
    argv:
      - grep
      - -qrHnie
      - libreoffice/ppa
      - /etc/apt/sources.list.d/
  register: libreoffice_ppa_grep
  check_mode: False
  changed_when: False
  failed_when: False

- name: Add the LibreOffice Fresh PPA
  add_ppa:
    name: ppa:libreoffice/ppa
  become: True
  when: libreoffice_ppa_grep.rc != 0

- name: Upgrade to install newer LibreOffice packages
  apt:
    update_cache: True
    upgrade: dist
  become: True
  when: libreoffice_ppa_grep.rc != 0

- name: Install LibreOffice theme packages
  apt:
    pkg:
    - libreoffice-style-breeze
    - libreoffice-style-elementary
    - libreoffice-style-galaxy
    state: present
  become: True
