- name: Install apt packages
  ansible.builtin.apt:
    pkg:
    - audacity
    - blender
    - build-essential
    - curl
    - dconf-cli
    - dconf-editor
    - dkms
    - easytag
    - exiv2
    - flake8
    - fonts-alegreya-sans
    - fonts-lato
    - fonts-powerline
    - fonts-roboto
    - fonts-roboto-hinted
    - fonts-roboto-slab
    - gifsicle
    - gimp
    - gnome-tweaks
    - gnucash
    - gparted
    - gscan2pdf
    - handbrake
    - handbrake-cli
    - htop
    - iftop
    - imagemagick
    - inkscape
    - jq
    - ldap-utils
    - lsdvd
    - mesa-utils
    - minicom
    - mkvtoolnix
    - nfs-common
    - nmap
    - openscad
    - pandoc
    - pdftk-java
    - proxytunnel
    - pv
    - python-is-python3
    - python3-pip
    - scdaemon
    - screen
    - shellcheck
    - smbclient
    - sqlite3
    - tmux
    - tofrodos
    - traceroute
    - udiskie
    - universal-ctags
    - unrar
    - vim-gtk3
    - vlc
    - whois
    - xclip
    - yq
    - yubikey-manager
    state: present
    update_cache: true
    cache_valid_time: 600
  become: true

- name: Install pip packages via pipx
  community.general.pipx:
    name: "{{ item }}"
    state: present
  loop:
  - ansible-lint
  - easyeda2kicad
  - linode-cli
  - mdv
  - mpremote
  - platformio
  - poetry
  - ruff
  - pre-commit
  - s3cmd
  - scons
  - yt-dlp

- name: Install poetry-dynamic-versioning into poetry virtualenv
  community.general.pipx:
    name: poetry
    inject_packages: poetry-dynamic-versioning
    state: inject
