- include_tasks: google-chrome.yml
- include_tasks: packages.yml
- include_tasks: pipx.yml
- include_tasks: ubuntubudgie-backports-ppa.yml
- include_tasks: virtualbox-guest.yml

- include_tasks: libreoffice-ppa.yml
  when: ansible_distribution_release not in ppa_exclude_releases
