- name: 'Include common package tasks'
  ansible.builtin.include_tasks: common.yml

- name: 'Include package tasks for {{ ansible_facts["distribution"] }} {{ ansible_facts["distribution_version"] }}'
  ansible.builtin.include_tasks: '{{ item }}'
  with_first_found:
  - files:
    - '{{ ansible_facts["distribution"] | lower }}-{{ ansible_facts["distribution_version"] }}.yml'
  - skip: true
