- name: Install apt packages
  apt:
    pkg:
    - audacity
    - blender
    - build-essential
    - curl
    - dconf-cli
    - dconf-editor
    - dkms
    - easytag
    - exiv2
    - exuberant-ctags
    - flake8
    - gifsicle
    - gimp
    - gnome-tweaks
    - gnucash
    - gparted
    - gscan2pdf
    - handbrake
    - handbrake-cli
    - htop
    - iftop
    - imagemagick
    - inkscape
    - jq
    - ldap-utils
    - lsdvd
    - mesa-utils
    - minicom
    - mkvtoolnix
    - nfs-common
    - nmap
    - openscad
    - pandoc
    - pdftk-java
    - proxytunnel
    - pv
    - python-is-python3
    - python3-pip
    - scdaemon
    - screen
    - shellcheck
    - smbclient
    - sqlite3
    - tmux
    - tofrodos
    - traceroute
    - unrar
    - vim-gtk3
    - vlc
    - whois
    - xclip
    - yubikey-manager
    - yubioath-desktop
    state: present
  become: true
