- name: Install pip packages via pipx
  community.general.pipx:
    name: "{{ item }}"
    state: present
  with_items:
  - ansible-lint
  - black
  - cookiecutter
  - cruft
  - flake8
  - isort
  - linode-cli
  - mdv
  - mpremote
  - platformio
  - poetry
  - pre-commit
  - scons
  - thonny
  - yt-dlp

- name: Install poetry-dynamic-versioning into poetry virtualenv
  community.general.pipx:
    name: poetry
    inject_packages: poetry-dynamic-versioning
    state: inject
