- name: Install cabal-install
  apt:
    pkg: '{{ item }}'
    state: present
  become: True
  register: cabal_install_apt_results
  with_items:
  - cabal-install

- name: cabal-install package installation output
  debug: var=cabal_install_apt_results.results.0.stdout_lines
  when: cabal_install_apt_results is changed

- name: Update list of known cabal packages
  command: cabal update
  changed_when: False

- name: Install shellcheck
  command: cabal install shellcheck
  args:
    creates: ~/.cabal/bin/shellcheck
  register: shellcheck_installed

- name: Symlink shellcheck to ~/.local/bin
  file:
    src: ../../.cabal/bin/shellcheck
    dest: ~/.local/bin/shellcheck
    state: link
  when: shellcheck_installed is changed
