- name: Install cabal-install
  apt:
    pkg: cabal-install
    state: present
  become: true

- name: Check if shellcheck is installed
  stat:
    path: ~/.cabal/bin/shellcheck
  register: shellcheck_stat_result

- name: Update list of known cabal packages
  command: cabal new-update
  changed_when: false
  when: not shellcheck_stat_result.stat.exists

- name: Retrieve ghc version
  shell: |
    ghc --version | awk '{print $NF}'
  register: cabal_version_number
  when: not shellcheck_stat_result.stat.exists

  # Workaround for https://github.com/haskell/cabal/issues/5516
- name: Create ~/.cabal/store/ghc-{{ cabal_version_number.stdout }}/package.db
  file:
    path: ~/.cabal/store/ghc-{{ cabal_version_number.stdout }}/package.db
    state: directory
  when: not shellcheck_stat_result.stat.exists and cabal_version_number.stdout !=
    ""

- name: Install shellcheck
  command: cabal new-install ShellCheck
  args:
    creates: ~/.cabal/bin/shellcheck
  when: not shellcheck_stat_result.stat.exists

- name: Symlink shellcheck to ~/.local/bin
  file:
    src: ../../.cabal/bin/shellcheck
    dest: ~/.local/bin/shellcheck
    state: link
