- name: Check if the current system is a Virtualbox guest
  shell: |
    lspci | grep -qie 'Virtualbox'
  register: virtualbox_guest_check
  check_mode: False
  changed_when: False
  failed_when: False

- name: Install Virtualbox guest additions
  apt:
    pkg:
    - virtualbox-guest-dkms
    - virtualbox-guest-x11
    state: present
  become: True
  when: virtualbox_guest_check.rc == 0
