- name: Check if the Powerline fonts are installed
  shell: fc-list | grep "for Powerline"
  register: powerline_font_check
  check_mode: false
  changed_when: false
  failed_when: false

- name: Install needed system fonts
  command: '{{ ansible_user_dir }}/.dotfiles/bin/install-fonts'
  become: true
  when: powerline_font_check.rc > 0
