- name: Set up smkent's authorized_keys
  ansible.posix.authorized_key:
    user: smkent
    state: present
    key: '{{ item }}'
  with_file:
  - yubikey.pub

- name: Install ssh packages
  apt:
    pkg:
    - ssh
    state: present
  become: true
