  - name: Install VirtualBox if not already on a virtual machine
    when: "ansible_facts['virtualization_role'] != 'guest'"
    block:
      - name: Add VirtualBox apt repository
        ansible.builtin.deb822_repository:
          name: virtualbox
          types: deb
          uris:
            - "https://download.virtualbox.org/virtualbox/debian"
          suites:
            - "{{ ansible_facts['distribution_release'] }}"
          components:
            - contrib
            - non-free
          signed_by: |-
            -----BEGIN PGP PUBLIC KEY BLOCK-----

            mQINBFcZ9OEBEACSvycoAEIKJnyyIpZ9cZLCWa+rHjXJzPymndnPOwZr9lksZVYs
            12YnsEy7Uj48rTB6mipbIuDDH9VBybJzpu3YjY7PFTkYAeW6WAPeJ8RcSGXsDvc0
            fQ8c+7/2V1bpNofc9vDSdvcM/U8ULQcNeEa6DI4/wgy2sWLXpi1DYhuUOSU10I97
            KHPwmpWQPsLtLHEeodeOTvnmSvLX1RRl32TPFLpLdjTpkEGS7XrOEXelqzMBQXau
            VUwanUzQ2VkzKnh4WecmKFT7iekOFVHiW0355ErL2RZvEDfjMjeIOOa/lPmW7y4F
            fHMU3a3sT3EzpD9ST/JGhrmaZ+r5yQD4s4hn1FheYFUtUN0dqHe9KgPDecUGgh4w
            rGnm0nUQsmQLKGSFXskqt26IiERdRt1eXpR9C5yufCVZfYpSsoG/mIHAt9opXFqi
            ryJqzx5pfQkOLTz9WErThHK1399jyXJwYGKLyddHFQEdy3u3ELM8Kfp7SZD/ERVq
            t2oA8jsr24IOyL16cydzfSP2kAV1r30bsF/1Q4qq6ii/KfDLaI0KEliBLQuB9jrA
            6XQ69VLtkNPgiWzVMclg+qW1pA8ptXqXLMxi4h5EmE5GOhsihuwkwhhBmFqGT1RJ
            EGlc/uiHWQskOW3nhQ3Epd6xhCUImy8Eu83YRxS6QriH6K8z5LgRSdg9nwARAQAB
            tElPcmFjbGUgQ29ycG9yYXRpb24gKFZpcnR1YWxCb3ggYXJjaGl2ZSBzaWduaW5n
            IGtleSkgPGluZm9AdmlydHVhbGJveC5vcmc+iQI3BBMBCgAhBQJXGfThAhsDBQsJ
            CAcDBRUKCQgLBRYDAgEAAh4BAheAAAoJEKL2g8UpgK7P49QP/39dH+lFqlD9ruCV
            apBKVPmWTiwWbqmjxAV35PzG9reO7zHeZHil7vQ6UCb6FGMgZaYzcj4Sl9xVxfbH
            Zk7lMgyLDuNMTTG4c6WUxQV9UH4i75E1IBm9lOJw64bpbpfEezUF/60PAFIiFBvD
            34qUAoVKe49PbvuTy98er5Kw6Kea880emWxU6I1Q1ZA80+o2dFEEtQc+KCgfWFgd
            O757WrqbTj6gjQjBAD5B4z5SwBYMg1/TiAYF0oa+a32LNhQIza/5H3Y+ufMfO3tY
            B/z1jLj8ee5lhjrv0jWvvfUUeIlq5pNoOmtNYFS+TdkO0rsqEC6AD0JRTKsRHOBu
            eSj7SLt8gmqy7eEzRCMlYIvoQEzt0/JuTQNJjHCuxH1scV13Q3bK6SmxqlY46tf5
            Ljni9Z4lLJ7MB1BF2MkHuwQ7OcaEgUQBZSudzPkpRnY0AktiQYYP4Q1uDp+vfvFp
            GTkY1pqz3z2XD66fLz0ea5WIBBb3X/uq9zdHu8BTwDCiZlWLaDR5eQoZWWe+u+5J
            NUx1wcBpC1Hr2AnmuXBCRq+bzd8iaB8qxWfpCAFZBksSIW2aGhigSeYdx1jpjOob
            xog4qbuo5w1IUh8YLHwQ6uM12CqwC1nZadLxG0Fj4KoYbvp0T5ryBM3XD+TVGjKB
            m/QHLqabxZBbuJT0Cw2dRtW/ty5ZuQINBFcZ9OEBEADEY+YveerQjzzy5nA1FjQG
            XSaPcjy4JlloRxrUyqlATA0AIuK7cwc7PVrpstV8mR9qb38fdeIoY1z1dD3wnQzJ
            lbDfZhS5nGMzk9AANd6eJ2KcWI3qLeB//4fr2pPS0piOG4qyW4IhY4KeuCwusE6d
            IyDBg2XEdpG1IesSDaqNsvLZjPFEBNiCIkqrC7XSmoPNwHkKGj5LeD1wAE914cn2
            a04IlbXiT46V9jjJFnNem/Co0u+2e2J3oReNmHvbb62OC57rqeBxqBplXg9tvJk/
            w0A3bXxUrfz83tY6vDYoFdwJDudaJJWQjvqpYnySXMJYT6KoE4Xgl5fNcbNIVUpU
            k74BcWD9PZVadSMN7FWZzMfVsbTMmUA22tuDKD6hrF6ysCelex4YO44kSH7dhXu5
            ANtZ2BFfRZvdjTQoblOI8C9cy/iX74vvG8OZarFG+u/kon3+xcAgY5KceUVbostO
            0n3V8iK0gMQWH8sR8vXH+oV4GqHUEQURax2XM2Tt7Ra5XGcQaYDIkNPKSVVVtTk5
            3OU/bNoBofAbwd4eOZOf9ag5ZVIIaoubMOEiveGYde4AEVE7krSNcYh/C48iCVKr
            eOyS26AVA15dAvnKTAqxJqICUSQ9zjGfTp1obhXCkMAy0m+AxNVEfSzFznQLHtWK
            zEGr+zCsvj1R8/qlMpHBXQARAQABiQIfBBgBCgAJBQJXGfThAhsMAAoJEKL2g8Up
            gK7PKpQP+wY9zLgnJeqrvNowmd70afd8SVge9BvhLh60cdG+piM5ZuEV5ZmfTFoX
            XPHzOo2dgt6VYTE9JO72Jv7MyzJj3zw3G/IcJQ6VuQwzfKkFTD+IeOiXX2I2lX1y
            nFv24rs1MTZ4Px1NJai7fdyXLiCl3ToYBmLafFpfbsVEwJ8U9bCDrHE4KTVc9IXO
            KQ5/86JaIPN+JJLHJoO2EBQC08Cw3oxTDFVcWZ/IWvEFeqyqRSyoFMoDkjLYsqHS
            we1kEoMmM2qN20otpKYq8R+bIEI5KKuJvAts/1xKE2cHeRvwl5kcFw/S3QQjKj+b
            LCVTSRZ6EgcDDmsAPKt7o01wmu+P3IjDoiyMZJQZpZIA2pYDxruY+OLXpcmw78Gq
            lTXb4Q9Vf47sAE8HmHfkh/wrdDeEiY9TQErzCBCufYbQj7sgttGoxAt12N+pUepM
            MBceAsnqkF6aEa4n8dUTdS2/nijnyUZ2rDVzikmKc0JlrZEKaw8orDzg8fXzfHIc
            pTrXCmFLX5BzNQ4ezAlw0NZG/qvhSBCuAkFiibfQUal8KLYwswvGJFghuQHsVTkf
            gF8Op7Br7loTNnp3yiI0jo2D+7DBFqtiSHCq1fIgktmKQoVLCfd3wlBJ/o9cguT4
            Y3B83Y34PxuSIq2kokIGo8JhqfqPB/ohtTLHg/o9RhP8xmfvALRDmQGiBEvy0LAR
            BACPBH1AUv6krDseyvbL63CWS9fw43iReZ+NmgmDp4/sPsYHLduQrxKSqiK7fgFF
            E+fas/7DCaZXIQW6hnqeD3CgnX0w1+gYiyqEuPY1LQH9okBR5o92/s2FLm7oUN4R
            NGv6vWoNSH1ZiRHknL5D0pKSGTKU+pG6cBYWJytAuJZHfwCguS55aPZuXfhjaWsX
            G8TF6GH0K8ED/RY3KbirJ7rueK/7KL7ziwqn4CdhQSLOhbZ/R2E0bknJQDo+vWJc
            iRRRpTe+AG59ctgDF7lEXpjvCms0atyKtE8hObNaMJ5p48l/sgFLLEujqiq4tByA
            n2hDOf0s7YrfruIY+HHkBSI9XbwH9nPlsQq8WNsTWTzPrw+ZlQ7vAEuuA/9cJ/4q
            YUOq1pg3i/GqH+2dbRHOFH6idXr5YrdB3cYW8jORagOcwdQHeV/0CaTZVMyMhTVj
            tIiUt+UR/96CHKxedg0giHwD61GidpUVBUYSaDhjOKE3jwf6/jo5714e4+ZfL3y1
            Q2N4HzfK/gEkvPZby/o8WX2N7vUcxfztQ8yq6bRJT3JhY2xlIENvcnBvcmF0aW9u
            IChWaXJ0dWFsQm94IGFyY2hpdmUgc2lnbmluZyBrZXkpIDxpbmZvQHZpcnR1YWxi
            b3gub3JnPohgBBMRAgAgBQJL8tCwAhsDBgsJCAcDAgQVAggDBBYCAwECHgECF4AA
            CgkQVEIqS5irUTmlvwCeIjsPZ0I9HhLmlS9dLjk397Y5rncAn3kBXUPRIWb83FMx
            RwqS85rTCZyouQINBEvy0LAQCAC/pkqDW6H99qQdyW8zvQL5xj6CUcvlTpL5VkaI
            RDVwRNbiFoWsVMv2jdhmlJEoh5N+aXYcAzLv0HaiZBSDmTO6fqMMuPRHyIioQQUF
            NW4hRI7sdMkYvd2oZcxnzRCLdzG+s42EmzxE4F29eT/FA7o/QBj2nDbomVqM9jCX
            KB5/jSJ0W3Uf7I8b7go0AawJT9vVARRMFjz4A7h6QfjeSO9sPHSC1Dx5Fmd3u4y0
            8W+o6w2kxXRYT9wfMFuGl4MWVJ+f6KPyRhqRCEaa/mz7lXhQdfeGqW8psDHKmoNn
            pPEq5Rl4aDIJOppwYJhnDELv+k8JJ6R1JM9hJUWTG8zv9sLzAAMFCAC6pagGYEK8
            Dh+3SV6dXjBLNghmj5qnx6GoCXwCDTEFXeWUnszZrqM7PTKLyrfKZjOhluydpQSG
            Y7TqDBJJ6emLyNNJV92IQ21eN/h9i0wB97pu8jwvi7RjD0vSkDHhOpSr9vJm9EeE
            SU1Z+mEKOjz2AONjRLplbBNt9kbXmSWpIP8XMFkU+1KTuNbfi+h4muOJWKkAGcT7
            bMUlqbZQjZ2O0RtwDjThxHvw8NhRkxPDYHVxE4uRRobhPquq4NsCQkMc7LlRilXZ
            CS5mrabHw5+edullNWaQtGuKGlQXGfM4kEhGt7b/XIiyhI5bsh60o8Mz0KuFpClp
            9B7c78+QBzTbiEkEGBECAAkFAkvy0LACGwwACgkQVEIqS5irUTnqqACgtXuTbe2b
            72sgKdc6gGRKPhLDoEMAmgLwGVN3a4CqewQL+03bqfcKczNHmQGiBEh7C8oRBACt
            OAieuw71PWaeBpi3djCX2sbZ3pqvfMsTaUb4E8Jo6ylC5xOarc4PUQt5/fHaFwOg
            P+MF11pt8LunY7nXgFNufmXWxAwjaB26EqAF9CytxJS7viu9tjEFqWQIL+2GHE1s
            EAevr8EvVr7fnmCUuY06nb1WvaOlL1VO2DAs+aJ2fwCguhlZozqrrFyhO7XjRX9i
            mHXbIvsD/2ntslEsaYgnTaNAOCGVUZi4kUQKVZrELgYpLo0ZWq6fbAskgI5qFe4X
            gP0TqLoI4KLg5OaMXdWDhboaJ3Ln9JgQnjLS3fJG75Lu3QF/6nPWYKcuQILLOcsX
            PthHDxyvRqTv5uUmiNRSDJSMLMA2LgUjzKJ7mEzDZ/uL8jZqjfR2A/9r+H4wct/Y
            S0Xmm2JWZxDlT+D27zF0zKzHVINr2eSK8K5mIhOZxAJN37ayqVcegz23JII3MQKO
            uvuH7pBzGEY1IiT6gvAI7WjVm+pRU+TarVwytoANWOvTWfid2Y/OgClJ4iqnhj/e
            gM/c3A7KrGG4Q/Tj1rHqnB+rRilVoYQbaLRRU3VuIE1pY3Jvc3lzdGVtcywgSW5j
            LiAoeFZNIFZpcnR1YWxCb3ggYXJjaGl2ZSBzaWduaW5nIGtleSkgPGluZm9Admly
            dHVhbGJveC5vcmc+iGAEExECACAFAkh7C8oCGwMGCwkIBwMCBBUCCAMEFgIDAQIe
            AQIXgAAKCRDc+fh7bfvLrnOHAJwLYTeiZC3HyO6758GKiMHZ2VTO5gCfXb1PdW17
            wqGKz5nyka9qpjOAs2C5Ag0ESHsL0BAIAKVaUE5yk8vsXkbjCPxrs2R7XuqrLp2/
            KSdjV7wi1dhwOgFUNObNMsK3K683mxmMnT65mJ/HqiXgW9WY5PgLzrHnEA27O7v2
            ol3O86wkr5BHaaStsLpkDIMItywjPqZkp7KHFDRXrhGTiHLg0D6YQB/+GRlxWZTA
            mB6F+ZGwQj3k9+q7kUd5Gj+LbmC6RA/7yrxgLgCRpdbilGQdxV2mGanX2qoA0Fu1
            nVXDWw3lPU95za3iAXVle89YRNFRK2WxV0hIFhqA/DndR1Y8M9fL4jDYXRtbDnUT
            khfZiH9MiuDVSzcXN0cUApaovLlnvDaPB7iLTi8SmIMdO6YYME7JwCsAAwUIAISg
            j2zdQC4TilbTGifMMJ0m3dVbjaoApuTaQc+vulCIhr/rf1DNV7gtLNd+CRx67xty
            VKfxPWL5vBL9OBCWcCdYY2iCplXv8gUZmwRtTN/B0+Ce07Re+bWUe/wBl7z6YBYQ
            nmtOxK55OXEgzv3/wL7L8Mt3co8AeO1qy4kM66JFnq8Scw81Axx4lcIPW1q17moy
            gSwD/1YbEgFMQHs/8V8aqB9xIs5yOdsA4VWj32V7ymW2V+sx4oKoiZiYuGZOjgGp
            ZlQMxgUaORO0PPRSqnCmuV9zujmd28Fljdrb+WDvc/xDwiKgnN/FKpMczPur8keO
            GpPSeUmZPaxkNmKbqGyISQQYEQIACQUCSHsL0AIbDAAKCRDc+fh7bfvLronZAKCf
            iCvC2s61vA1x/YJ9QUPn4lCpjgCbB4dSVAHE/imWR02yFhqz32NqKPU=
            =RLBu
            -----END PGP PUBLIC KEY BLOCK-----
          architectures: amd64
          state: present
          enabled: true
        register: virtualbox_apt_repo
        become: true

      - name: Install VirtualBox
        ansible.builtin.apt:
          pkg:
            - virtualbox-7.2
          state: present
          update_cache: true
          cache_valid_time: "{{ 0 if virtualbox_apt_repo.changed else 600 }}"
        become: true

      - name: "Ensure {{ ansible_facts['user_id'] }} is in the vboxusers group"
        ansible.builtin.user:
          name: "{{ ansible_facts['user_id'] }}"
          groups:
            - vboxusers
          append: true
        become: true

      - name: Add workaround for VirtualBox XWayland crash on screen resume
        ansible.builtin.copy:
          dest: /etc/environment.d/90-virtualbox.conf
          content: |
            VBOX_DESKTOPWATCHDOGPOLICY_SYNTHTEST=Disabled
        become: true
