- name: Add Docker apt repository
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: "https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}"
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: stable
    signed_by: "https://download.docker.com/linux/ubuntu/gpg"
    state: present
    enabled: true
  register: docker_apt_repo
  become: true

- name: Install Docker
  ansible.builtin.apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - docker-buildx-plugin
    - docker-compose-plugin
    state: present
    update_cache: true
    cache_valid_time: "{{ 0 if docker_apt_repo.changed else 600 }}"
  become: true

- name: Ensure /etc/docker exists
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: "0755"
  become: true

- name: Ensure Docker log rotation is configured
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    mode: "0644"
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "10",
          "max-file": "3",
          "compress": "true"
        }
      }
  become: true
