- name: Add Docker apt repository
  ansible.builtin.deb822_repository:
    name: docker
    uris:
    - "https://download.docker.com/linux/ubuntu"
    suites:
    - "{{ ansible_facts['distribution_release'] }}"
    components:
    - stable
    signed_by: "https://download.docker.com/linux/ubuntu/gpg"
    architectures: amd64
    state: present
    enabled: true
  register: docker_apt_repo
  become: true

- name: Install Docker
  ansible.builtin.apt:
    pkg:
    - docker-ce
    state: present
    update_cache: true
    cache_valid_time: "{{ 0 if docker_apt_repo.changed else 600 }}"
  become: true

- name: Create link to docker executables
  ansible.builtin.file:
    src: "/usr/libexec/docker/cli-plugins/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    owner: root
    group: root
    state: link
  become: true
  with_items:
  - docker-buildx
  - docker-compose
