- name: Add GitHub CLI apt repository
  ansible.builtin.deb822_repository:
    name: github-cli
    uris:
    - "https://cli.github.com/packages"
    suites:
    - stable
    components:
    - main
    signed_by: "https://cli.github.com/packages/githubcli-archive-keyring.gpg"
    architectures: amd64
    state: present
    enabled: true
  register: github_cli_apt_repo
  become: true

- name: Update packages cache
  apt:
    update_cache: true
  become: true
  when: github_cli_apt_repo.changed

- name: Install GitHub CLI
  apt:
    pkg:
    - gh
    state: present
  become: true
