- name: Add Google apt repository
  ansible.builtin.deb822_repository:
    name: google
    uris:
    - "http://dl.google.com/linux/chrome/deb"
    suites:
    - stable
    components:
    - main
    signed_by: "https://dl.google.com/linux/linux_signing_key.pub"
    architectures: amd64
    state: present
    enabled: true
  register: google_apt_repo
  become: true

- name: Update packages cache
  apt:
    update_cache: true
  become: true
  when: google_apt_repo.changed

- name: Install Google Chrome
  apt:
    pkg:
    - google-chrome-stable
    state: present
  become: true
