- name: Add Google apt repository
  ansible.builtin.deb822_repository:
    name: google
    uris:
    - "http://dl.google.com/linux/chrome/deb"
    suites:
    - stable
    components:
    - main
    signed_by: "https://dl.google.com/linux/linux_signing_key.pub"
    architectures: amd64
    state: present
    enabled: true
  register: google_apt_repo
  become: true

- name: Install Google Chrome
  ansible.builtin.apt:
    pkg:
    - google-chrome-stable
    state: present
    update_cache: true
    cache_valid_time: "{{ 0 if google_apt_repo.changed else 600 }}"
  become: true
