- name: Add Google apt repository
  ansible.builtin.deb822_repository:
    name: google
    uris:
    - "http://dl.google.com/linux/chrome/deb"
    suites:
    - stable
    components:
    - main
    signed_by: "https://dl.google.com/linux/linux_signing_key.pub"
    state: present
    enabled: true
  become: true

- name: Install Google Chrome
  apt:
    pkg:
    - google-chrome-stable
    state: present
  become: true
