- name: Install Libreoffice Fresh PPA
  add_ppa:
    repo: ppa:libreoffice/ppa
  register: libreoffice_ppa
  become: true

- name: Upgrade to install newer LibreOffice packages
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
    cache_valid_time: "{{ 0 if libreoffice_ppa.changed else 600 }}"
  become: true

- name: Install LibreOffice
  ansible.builtin.apt:
    pkg:
    - libreoffice
    state: present
    update_cache: true
    cache_valid_time: 600
  become: true
