- name: Install MakeMKV Beta PPA
  add_ppa:
    repo: ppa:heyarje/makemkv-beta
  become: true
  register: makemkv_ppa

- name: Install MakeMKV
  ansible.builtin.apt:
    pkg:
    - makemkv-bin
    - makemkv-oss
    state: present
    update_cache: true
    cache_valid_time: "{{ 0 if makemkv_ppa.changed else 600 }}"
  become: true
