- name: Add Signal apt repository
  ansible.builtin.deb822_repository:
    name: signal
    uris:
    - "https://updates.signal.org/desktop/apt"
    suites:
    - xenial
    components:
    - main
    signed_by: "https://updates.signal.org/desktop/apt/keys.asc"
    architectures: amd64
    state: present
    enabled: true
  register: signal_apt_repo
  become: true

- name: Install Signal
  ansible.builtin.apt:
    pkg:
    - signal-desktop
    state: present
    update_cache: true
    cache_valid_time: "{{ 0 if signal_apt_repo.changed else 600 }}"
  become: true
