- name: Check if Zoom is installed
  command: dpkg-query -l zoom
  register: zoom_installed
  failed_when: zoom_installed.rc > 1
  check_mode: false
  changed_when: false

- name: Install Zoom
  apt:
    deb: https://zoom.us/client/latest/zoom_amd64.deb
    state: present
  become: true
  when: zoom_installed.rc != 0
