- name: Check if MATE is installed
  command: dpkg-query -l mate-desktop
  register: mate_installed
  failed_when: mate_installed.rc > 1
  check_mode: False
  changed_when: False

- include_tasks: general.yml
  when: mate_installed.rc == 0

- include_tasks: mate-terminal.yml
  when: mate_installed.rc == 0

- include_tasks: text-editor.yml
  when: mate_installed.rc == 0
