- name: Check if MATE is installed
  command: dpkg-query -l mate-desktop
  register: mate_installed
  failed_when: mate_installed.rc > 1
  check_mode: false
  changed_when: false

- include_tasks: '{{mate_preferences_item}}'
  with_items:
  - mate-general-preferences.yml
  - mate-power-manager.yml
  - mate-terminal.yml
  - mate-text-editor.yml
  loop_control:
    loop_var: mate_preferences_item
  when: mate_installed.rc == 0
