- name: Set power manager preferences
  dconf: key={{item.key}} type={{item.type}} value="{{item.val}}"
  with_items:
  - {key: /org/mate/power-manager/button-lid-ac, val: nothing, type: string}
  - {key: /org/mate/power-manager/button-lid-battery, val: nothing, type: string}
  - {key: /org/mate/power-manager/button-power, val: "{{ 'shutdown' if ansible_form_factor
      == 'Desktop' else 'suspend' }}", type: string}
