- name: Set mate-terminal preferences
  dconf: key={{item.key}} type={{item.type}} value="{{item.val}}"
  with_items:
  - {key: /org/mate/terminal/profiles/smkent/allow-bold, val: true, type: bool}
  - {key: /org/mate/terminal/profiles/smkent/alternate-screen-scroll, val: true,
    type: bool}
  - {key: /org/mate/terminal/profiles/smkent/background-color, val: "#000000000000",
    type: string}
  - {key: /org/mate/terminal/profiles/smkent/background-darkness, val: 0.8, type: float}
  - {key: /org/mate/terminal/profiles/smkent/background-type, val: transparent, type: string}
  - {key: /org/mate/terminal/profiles/smkent/bold-color, val: "#000000000000", type: string}
  - {key: /org/mate/terminal/profiles/smkent/bold-color-same-as-fg, val: true, type: bool}
  - {key: /org/mate/terminal/profiles/smkent/default-show-menubar, val: false, type: bool}
  - {key: /org/mate/terminal/profiles/smkent/font, val: DejaVu Sans Mono for Powerline
      10, type: string}
  - {key: /org/mate/terminal/profiles/smkent/foreground-color, val: "#FFFFFFFFFFFF",
    type: string}
  - {key: /org/mate/terminal/profiles/smkent/palette, val: "#000000000000:#CCCC00000000:#4E4E9A9A0606:#C4C4A0A00000:#34346565A4A4:#757550507B7B:#060698209A9A:#D3D3D7D7CFCF:#555557575353:#EFEF29292929:#8A8AE2E23434:#FCFCE9E94F4F:#72729F9FCFCF:#ADAD7F7FA8A8:#3434E2E2E2E2:#EEEEEEEEECEC",
    type: string}
  - {key: /org/mate/terminal/profiles/smkent/scrollback-lines, val: 8192, type: int}
  - {key: /org/mate/terminal/profiles/smkent/scrollbar-position, val: hidden, type: string}
  - {key: /org/mate/terminal/profiles/smkent/silent-bell, val: false, type: bool}
  - {key: /org/mate/terminal/profiles/smkent/use-theme-colors, val: false, type: bool}
  - {key: /org/mate/terminal/profiles/smkent/use-system-font, val: false, type: bool}
  - {key: /org/mate/terminal/profiles/smkent/visible-name, val: smkent, type: string}
  - {key: /org/mate/terminal/global/profile-list, val: "'default'", type: array_present}
  - {key: /org/mate/terminal/global/profile-list, val: "'smkent'", type: array_present}
  - {key: /org/mate/terminal/global/default-profile, val: smkent, type: string}
