- name: Check if nemo is installed
  command: dpkg-query -l nemo
  register: nemo_installed
  failed_when: nemo_installed.rc > 1
  check_mode: False
  changed_when: False

- name: Set nemo preferences
  dconf: key={{item.key}} type={{item.type}} value="{{item.val}}"
  with_items:
      - { key: /org/nemo/preferences/default-folder-viewer,
            val: 'list-view', type: string }
      - { key: /org/nemo/preferences/enable-delete,
            val: 'false', type: bool }
      - { key: /org/nemo/preferences/never-queue-file-ops,
            val: 'true', type: bool }
      - { key: /org/nemo/preferences/show-computer-icon-toolbar,
            val: 'false', type: bool }
      - { key: /org/nemo/preferences/show-home-icon-toolbar,
            val: 'true', type: bool }
      - { key: /org/nemo/preferences/show-image-thumbnails,
            val: 'local-only', type: string }
      - { key: /org/nemo/preferences/show-location-entry,
            val: 'false', type: bool }
      - { key: /org/nemo/preferences/show-open-in-terminal-toolbar,
            val: 'true', type: bool }
      - { key: /org/nemo/preferences/show-reload-icon-toolbar,
            val: 'true', type: bool }
      - { key: /org/nemo/preferences/show-show-thumbnails-toolbar,
            val: 'true', type: bool }
      - { key: /org/nemo/preferences/size-prefixes,
            val: 'base-2', type: string }
      - { key: /org/nemo/preferences/menu-config/selection-menu-copy-to,
            val: 'true', type: bool }
      - { key: /org/nemo/preferences/menu-config/selection-menu-duplicate,
            val: 'true', type: bool }
      - { key: /org/nemo/preferences/menu-config/selection-menu-move-to,
            val: 'true', type: bool }
  when: nemo_installed.rc == 0
