- name: Retrieve UUID for current budgie-panel instance(s)
  command:
    argv:
    - dconf
    - read
    - /com/solus-project/budgie-panel/panels
  register: budgie_panels_dconf_output
  check_mode: false
  changed_when: false
  failed_when: false

- name: Remove existing budgie-panel(s) configuration
  command:
    argv:
    - dconf
    - reset
    - -f
    - /com/solus-project/budgie-panel/
  when: 'budgie_panels_dconf_output.stdout != "[''c01dale8-1977-1138-2187-deadbeef0000'']"'
  notify:
  - restart-budgie-panel

- name: Set dconf values from configuration file
  command:
    argv:
    - dconf
    - load
    - /
    stdin: "{{ lookup('file', 'dconf-settings.ini') }}"
  notify:
  - restart-budgie-panel

- name: Set budgie-panel menu label
  dconf:
    key: '/org/solus-project/budgie-panel/instance/budgie-menu/{c01dale8-1977-1138-2187-deadbeefa001}/menu-label'
    type: string
    value: '{{ ansible_hostname }}'
