- name: Check if Ghostscript types are enabled in ImageMagick
  command:
    argv:
      - grep
      - -qrHnie
      - disable ghostscript format types
      - /etc/ImageMagick-6/policy.xml
  register: imagemagick_policy_grep
  check_mode: False
  changed_when: False
  failed_when: False

- name: Enable Ghostscript types in ImageMagick
  command:
    argv:
      - sed
      - --in-place=.backup
      - -e
      - /disable ghostscript format types/,+6d
      - /etc/ImageMagick-6/policy.xml
    warn: False
  become: True
  when: imagemagick_policy_grep.rc == 0
